<?php

{% set data = [
	{id: 'norris', logo: '', date: '12.09'},
	{id: 'tyson', logo: ''},
	{id: 'kotler', logo: '', date: '29.08'},
	{id: 'forbs', logo: ''},
	{id: 'harari', logo: '', date: '29.05'},
	{id: 'besson', logo: '', date: ''},
	{id: 'belfort', logo: 'belfort'},
	{id: 'vujicic', logo: '', date: '20.06'},
	{id: 'taleb', logo: ''},
	{id: 'nurmagomedov', logo: ''},
	{id: 'schwarzenegger', logo: ''},
	{id: 'adizes', logo: '', photo_big: true },
	{id: 'gir', logo: ''},
	{id: 'pozner', logo: '', date: '29.05'},
	{id: 'brenson', logo: ''},
	{id: 'vries', logo: ''},
	{id: 'kavasaki', logo: ''},
	{id: 'sigal', logo: ''},
	{id: 'piontek', logo: '', date: '15.08'},
	{id: 'schiffman', logo: '', date: '08.08'},
	{id: 'goldsmit', logo: ''},
	{id: 'uelch', logo: ''},
	{id: 'tcukerberg', logo: ''},
	{id: 'raimen', logo: '', date: '20.06'},
	{id: 'tschohl', logo: 'sqi'},
	{id: 'ash', logo: 'ash', date: '13.06'},
	{id: 'cherni', logo: ''},
	{id: 'bogomolov', logo: '', date: '29.05'},
	{id: 'fridman', logo: 'amadeus', date: '01.08'},
	{id: 'arkhangelskyi', logo: 'arkhangelskyi'},
	{id: 'mann', logo: 'mann'},
	{id: 'petersyl', logo: 'petersyl', date: '08.08'},
	{id: 'andreeva', logo: '', date: '27.06'},
	{id: 'gilbert', logo: '', date: '27.06'},

	{id: 'kasatikova', logo: '', date: '19.09'},
	{id: 'galsev', logo: '', date: '29.09'},
	{id: 'mamontova', logo: '', date: '10.10'},
	{id: 'poletaev', logo: '', date: '10.10'},
	{id: 'brown', logo: '', date: '15.08'},
	{id: 'parrish', logo: '', date: '15.08'},
	{id: 'kurpatov', logo: '', date: '23.11'},
	{id: 'kolmanovsky', logo: '', date: '23.11'},
	{id: 'dubinin', logo: '', date: '23.11'},
	{id: 'sherbatih', logo: '', date: '23.11'},
	{id: 'kravchenko', logo: '', date: '15.08'},
	{id: 'garifullin', logo: '', date: '22.08'},
	{id: 'chekmaryov', logo: '', date: '29.08'},
	{id: 'smirnov', logo: '', date: '15.08'},
	{id: 'antonovv', logo: '', date: '15.08'},
	{id: 'shaukat', logo: '', date: '15.08'},
	{id: 'alepko', logo: '', date: '22.08'},
	{id: 'borozdin', logo: '', date: '15.08'},
	{id: 'belozerskaya', logo: '', date: '22.08'},
	{id: 'kozyk', logo: '', date: '15.08'},
	{id: 'shamenkov', logo: 'sod', date: '23.11'},
	{id: 'kormysh', logo: '', date: '29.08'},
	{id: 'gilemkhanova', logo: '', date: '15.08'},
	{id: 'shilova', logo: '', date: '22.08'},
	{id: 'metelitsa', logo: '', date: '22.08'},
	{id: 'troitskiy', logo: ''},
	{id: 'melnikov', logo: '', date: ''},
	{id: 'shimanskaya', logo: 'skillfolio', date: '22.08'},
	{id: 'isaev', logo: '', date: '22.08', version: 'biohacking' },
	{id: 'kovalev', logo: '', date: '22.08', version: 'biohacking' },
	{id: 'karkukli', logo: '', date: '22.08', version: 'biohacking' },
	{id: 'popovv', logo: '', date: '22.08', version: 'biohacking' },
	{id: 'skulachev', logo: '', date: '22.08'},
	{id: 'yan', logo: 'yan', date: '24.07'},
	{id: 'minin', logo: '', date: '24.07'},
	{id: 'elagina', logo: '', date: '01.08'},
	{id: 'zarubin', logo: '', date: '01.08'},
	{id: 'gazizulin', logo: 'gazizulin', date: '01.08'},
	{id: 'ukolova', logo: '', date: '08.08'},
	{id: 'hadarseva', logo: '', date: '01.08'},
	{id: 'krutilin', logo: '', date: '01.08'},
	{id: 'gvarishvili', logo: 'megafon', date: '01.08'},
	{id: 'tyazhkin', logo: '', date: '01.08'},
	{id: 'akhtar', logo: '', date: '01.08'},
	{id: 'baskaran', logo: '', date: '01.08'},
	{id: 'boronin', logo: 'tceh', date: '24.07'},
	{id: 'tsessarsky', logo: '', date: '24.07'},
	{id: 'baskakov', logo: '', date: '24.07'},
	{id: 'nikolenko', logo: '', date: '24.07'},
	{id: 'telenkov', logo: '', date: '24.07'},
	{id: 'soshnikov', logo: '', date: '24.07'},
	{id: 'yusupova', logo: '', date: '24.07'},
	{id: 'mitrofanov', logo: '', date: '24.07'},
	{id: 'beloborodov', logo: '', date: '24.07'},
	{id: 'mamlina', logo: '', date: '18.07'},
	{id: 'kitting', logo: '', date: '18.07'},
	{id: 'dembikova', logo: '', date: '18.07'},
	{id: 'panchenko', logo: '', date: '18.07'},
	{id: 'kuzmina', logo: '', date: '18.07'},
	{id: 'baranova', logo: 'baranova', date: '18.07'},
	{id: 'aguirre', logo: '', date: '18.07'},
	{id: 'londar', logo: '', date: '18.07'},
	{id: 'osipov', logo: '', date: '18.07'},
	{id: 'sivov', logo: '', date: '18.07'},
	{id: 'rulli', logo: '', date: '18.07'},
	{id: 'shamatawa', logo: '', date: '18.07'},
	{id: 'polousov', logo: 'trade', date: '18.07'},
	{id: 'kabanov', logo: '', date: '11.07'},
	{id: 'petrova', logo: '', date: '18.07'},
	{id: 'savkin', logo: '', date: '18.07'},
	{id: 'fuente', logo: '', date: '18.07'},
	{id: 'sentyurin', logo: '', date: '18.07'},
	{id: 'akhmedov_t', logo: '', date: '18.07'},
	{id: 'antonov', logo: 'targetorium', date: '18.07'},
	{id: 'protasova', logo: '', date: '18.07'},
	{id: 'berek', logo: '', date: '18.07'},
	{id: 'gutnik', logo: '', date: '18.07'},
	{id: 'semina', logo: '', date: '18.07'},
	{id: 'yurkov', logo: 'synergy-digital', date: '18.07'},
	{id: 'melnikov_a', logo: '', date: '18.07'},
	{id: 'khalilov', logo: '', date: '18.07'},
	{id: 'ignatenko', logo: '', date: '18.07'},
	{id: 'belousov', logo: '', date: '18.07'},
	{id: 'varnavski', logo: '', date: '18.07'},
	{id: 'nordstrem', logo: '', photo_big: true },
	{id: 'kovi', logo: ''},
	{id: 'kurtcveil', logo: ''},
	{id: 'goulman', logo: ''},
	{id: 'gladuel', logo: ''},
	{id: 'damborg', logo: '', date: '04.07'},
	{id: 'bushe', logo: 'ahsl', date: '27.06'},
	{id: 'dash', logo: '', date: '20.06'},
	{id: 'roach', logo: '', date: '20.06'},
	{id: 'sharova', logo: '', date: '20.06'},
	{id: 'mizitova', logo: '', date: '20.06'},
	{id: 'rudoy', logo: '', date: '20.06'},
	{id: 'kuvaev', logo: '', date: '20.06'},
	{id: 'mozg', logo: '', date: '20.06'},
	{id: 'dibirov', logo: '', date: '20.06'},
	{id: 'shakhray', logo: '', date: '20.06'},
	{id: 'zhuravleva', logo: '', date: '20.06'},
	{id: 'magomedovam', logo: '', date: '20.06'},
	{id: 'nechaeva', logo: '', date: '20.06'},
	{id: 'akhmedov', logo: '', date: '20.06'},
	{id: 'nadorshin', logo: '', date: '20.06'},
	{id: 'shans', logo: '', date: '20.06'},
	{id: 'belan', logo: '', date: '23.11'},
	{id: 'nuriakhmedov', logo: 'nuriakhmedov', date: '20.06'},
	{id: 'mikhaylova', logo: '', date: '20.06'},
	{id: 'drytko', logo: '', date: '20.06'},
	{id: 'gosman', logo: '', date: '20.06'},
	{id: 'medvedeva', logo: '', date: '20.06'},
	{id: 'marynovich', logo: '', date: '20.06'},
	{id: 'nikolova', logo: '', date: '20.06'},
	{id: 'zotov', logo: '', date: '20.06'},
	{id: 'kotyuh', logo: '', date: '20.06'},
	{id: 'afanasyev', logo: '', date: '20.06'},
	{id: 'chapkin', logo: '', date: '20.06'},
	{id: 'elkharbotly', logo: '', date: '20.06'},
	{id: 'shiyanov', logo: '', date: '20.06'},
	{id: 'raikes', logo: '', date: '20.06'},
	{id: 'gorbatovskiy', logo: '', date: '20.06'},
	{id: 'semenova', logo: '', date: '20.06'},
	{id: 'otb', logo: 'rosinter'},
	{id: 'skott', logo: ''},
	{id: 'reyss', logo: ''},
	{id: 'fillips', logo: ''},
	{id: 'rose', logo: '', date: '29.05'},
	{id: 'huffman', logo: 'huffman', date: '13.06'},
	{id: 'fraizer', logo: 'traffic-conversion'},
	{id: 'janda', logo: ''},
	{id: 'batyrev', logo: ''},
	{id: 'lundberg', logo: '', date: '29.05'},
	{id: 'horikiri', logo: '', date: '6.06'},
	{id: 'dwayer', logo: 'ehrmann', date: '6.06'},
	{id: 'chekushin', logo: 'just-magic', date: '13.06'},
	{id: 'breeze', logo: 'breeze', date: '13.06'},
	{id: 'kielberg', logo: ''},
	{id: 'nakhapetyan', logo: 'skolkovo'},
	{id: 'jhonston', logo: 'macroscope'},
	{id: 'finestein', logo: 'finestein'},
	{id: 'geraskov', logo: 'synergy_bot', date: '13.06'},
	{id: 'omar', logo: 'omar', date: '29.05'},
	{id: 'riy', logo: 'riy', date: '13.06'},
	{id: 'prunello', logo: 'prunello', date: '29.05'},
	{id: 'kostyukov', logo: '', date: '13.06'},
	{id: 'trubnikov', logo: 'siberica', date: '6.06'},
	{id: 'janibekyan', logo: 'comedy_club'},
	{id: 'sgibneva', logo: 'cdek', date: '29.05'},
	{id: 'chernyak', logo: 'big_money'},
	{id: 'borzov', logo: ''},
	{id: 'pryanishnikov', logo: 'wirldclass'},
	{id: 'borisov', logo: 'borisov', date: '6.06'},
	{id: 'queenie', logo: ''},
	{id: 'perekalskyi', logo: 'utkonos'},
	{id: 'zinyakova', logo: 'karo', date: '6.06'},
	{id: 'krishnev', logo: 'nike', date: '6.06'},
	{id: 'zarkov', logo: 'whiterabbit', date: '6.06'},
	{id: 'astakhov', logo: '', date: '29.05'},
	{id: 'kuchment', logo: 'hoff', date: '6.06'},
	{id: 'polyakova', logo: 'kfc', date: '6.06'},
	{id: 'binder', logo: 'lamoda'},
	{id: 'gorkov', logo: 'rosgeologiya'},
	{id: 'snesar', logo: 'vtb'},
	{id: 'popov', logo: '', date: '29.05'},
	{id: 'tadevosyan', logo: 'rambler'},
	{id: 'agabekov', logo: 'fabrika_okon'},
	{id: 'kravtzov', logo: 'expediciya'},
	{id: 'glushkov', logo: 'mone'},
	{id: 'vinner', logo: ''},
	{id: 'ushkova', logo: 'absolute', date: '6.06'},
	{id: 'zhurova', logo: ''},
	{id: 'ryzhkova', logo: '', date: '29.05'},
	{id: 'rouds', logo: ''},
	{id: 'kapustin', logo: 'stalogistic', date: '6.06'},
	{id: 'levchik', logo: 'traffic-masters', date: '13.06'},
	{id: 'teterina', logo: 'teterina', date: '29.05'},
	{id: 'cherkasova', logo: 'otkritiye'},
	{id: 'khimanych', logo: 'raiffeisen'},
	{id: 'sachkov', logo: '', date: '29.05'},
	{id: 'levi', logo: ''},
	{id: 'saad', logo: '', date: '29.05'},
	{id: 'danay', logo: ''},

	{id: 'filippov', logo: 'filippov', date: '29.05'},
	{id: 'kunitskiy', logo: 'bc', date: '20.06'},
	{id: 'koroma', logo: ''},
	{id: 'kirillova', logo: 'kirillova', date: '29.05'},
	{id: 'kurakov', logo: '', date: '29.05'},
	{id: 'singh', logo: '', date: '29.05'},
	{id: 'lovchev', logo: ''},
	{id: 'vasilenko', logo: 'vasilenko', date: '29.05'},
	{id: 'ridley', logo: ''},
	{id: 'pikova', logo: '', date: '29.05'},
	{id: 'sukhanova', logo: '', date: '29.05'},
	{id: 'tochilina', logo: ''},
	{id: 'ekinci', logo: 'ekinci', date: '29.05'},
	{id: 'mahmoudi', logo: '', date: '29.05'},
	{id: 'vinogrodsky', logo: '', date: '29.05'},
	{id: 'badun', logo: '', date: '29.05'},
	{id: 'kaabi', logo: '', date: '29.05'},
	{id: 'volek', logo: 'volek', date: '29.05'},
	{id: 'petrov', logo: 'petrov', date: '29.05'},
	{id: 'arutunyan', logo: 'henderson'},
	{id: 'maslennikov', logo: 'maslennikov', date: '29.05'},
	{id: 'perekua', logo: ''},
	{id: 'brodovskyi', logo: 'azimut'},
	{id: 'polzikov', logo: 'gp'},
	{id: 'trotsyuk', logo: 'yellow-black-white'},
	{id: 'ryasova', logo: 'finn_flare'},
	{id: 'artemyev', logo: 'cska1'},
	{id: 'assad', logo: '', date: '29.05'},
	{id: 'bardinceva', logo: 'okko'},
	{id: 'tcipkin', logo: ''},
	{id: 'anuryev', logo: 'litres'},
	{id: 'sidorina', logo: ''},
	{id: 'impolitov', logo: 'ya-efir'},
	{id: 'vasilchuk', logo: 'chaikhona'},
	{id: 'golub', logo: 'mailru'},
	{id: 'habarov', logo: 'trastbank'},
	{id: 'kunin', logo: 'goods'},
	{id: 'ten', logo: 'sports'},
	{id: 'dyakonov', logo: 'point'},
	{id: 'kapev', logo: 'exmo'},
	{id: 'zaripova', logo: 'lenta'},
	{id: 'manukovsky', logo: 'sothebys'},
	{id: 'rigikov', logo: '1c'},
	{id: 'fedorov', logo: '220v'},
	{id: 'pavlova', logo: 'odnoklassniki'},
	{id: 'tursunova', logo: 'vilgud'},
	{id: 'basha', logo: 'getresponse'},
	{id: 'chong', logo: 'mareven-food'},
	{id: 'adushev', logo: 'pochta_rossii'},
	{id: 'mitrovich', logo: 'novikov'},
	{id: 'georgiev', logo: 'rostelecom'},
	{id: 'talashkina', logo: 'gtmclinic'},
	{id: 'markov', logo: 'technonikol'},
	{id: 'chekanov', logo: 'megogo'},
	{id: 'spiridonov', logo: 'netologiya', date: '29.05'},
	{id: 'gulieva', logo: 'komus'},
	{id: 'kruglov', logo: 'vk'},
	{id: 'moskatov', logo: 'miel'},
	{id: 'metz', logo: 'hh', date: '29.05'},
	{id: 'karpinskaya', logo: 'monolit'},
	{id: 'muradov', logo: 'tvoy-dom'},
	{id: 'tkach', logo: 'vision'},
	{id: 'kalaev', logo: 'free'},
	{id: 'askeri', logo: 'askeri_gallery'},
	{id: 'lysukho', logo: 'pik-group'},
	{id: 'akucherena', logo: ''},
	{id: 'lebedev', logo: ''},
	{id: 'burashova', logo: 'marie-claire'},
	{id: 'karelin', logo: ''},
	{id: 'peresild', logo: 'galchonok'},
	{id: 'demchog', logo: ''},
	{id: 'elinson', logo: 'a1'},
	{id: 'pintosevich', logo: 'pintocevich'},
	{id: 'baranov', logo: ''},
	{id: 'goryacheva', logo: 'goryacheva', date: '29.05'},
	{id: 'belocerkovskiy', logo: 'uvenco'},
	{id: 'frolova', logo: 'artrussia'},
	{id: 'bokov', logo: ''},
	{id: 'myasnikov', logo: ''},
	{id: 'koreshkov', logo: ''},
	{id: 'gadjiev', logo: 'fight-nights'},
	{id: 'ryazansky', logo: ''},
	{id: 'peregudov', logo: 'vtb'},
	{id: 'avetov', logo: 'shb'},
	{id: 'krivoshapko', logo: 'pcm'},
	{id: 'kudryavtseva', logo: ''},
	{id: 'makarenko', logo: ''},
	{id: 'soloveva', logo: ''},
	{id: 'kukushkin', logo: ''},
	{id: 'belonoshenko', logo: 'babyclub'},
	{id: 'schneider', logo: ''},
	{id: 'tarasov', logo: '', date: '29.05'},
	{id: 'makarenkov', logo: 'ripol-classic'},
	{id: 'vlasov', logo: 'logistics'},
	{id: 'voinov', logo: 'dpd'},
	{id: 'orlovskyi', logo: 'firstross'},
	{id: 'vladimirova', logo: ''},
	{id: 'saysembaev', logo: '', photo_big: true },
	{id: 'galicyn', logo: ''},
	{id: 'karabet', logo: ''},
	{id: 'goldort', logo: 'cdek'},
	{id: 'hashimov', logo: ''},
	{id: 'husainov', logo: 'etazhi'},
	{id: 'mitryushin', logo: '', date: '29.05'},
	{id: 'muhoryapov', logo: ''},
	{id: 'kolmogorov', logo: 'sushi'},
	{id: 'kaplina', logo: 'kaplina', date: '29.05'},
	{id: 'berg', logo: 'berg', date: '29.05'},
	{id: 'zurinskas', logo: ''},
	{id: 'bordykova', logo: 'bordykova', date: '29.05'},
	{id: 'kornilov', logo: 'synergy', date: '29.05'},
	{id: 'sanei', logo: '', date: '29.05'},
	{id: 'feigin', logo: 'feigin', date: '29.05'},
	{id: 'lvova', logo: 'hh', date: '29.05'},
	{id: 'sharipov', logo: '', date: '29.05'},
	{id: 'baytasov', logo: 'baytasov', date: '29.05'},
	{id: 'eliseev', logo: 'eliseev', date: '29.05'},
	{id: 'tkachenko_a', logo: ''},
	{id: 'fedorenko', logo: ''},
	{id: 'aivanov', logo: ''},
	{id: 'dobrovinsky', logo: ''},
	{id: 'vladimirskaya', logo: 'vladimirskaya'},
	{id: 'mardoyan', logo: ''},
	{id: 'makhota', logo: ''},
	{id: 'babaev', logo: 'babaev', date: '29.05'},
	{id: 'imayeva', logo: 'nafi'},
	{id: 'assovskaya', logo: ''},
	{id: 'akubardiya', logo: ''},
	{id: 'granovskiy', logo: 'livecoffee'},
	{id: 'safronov', logo: '', date: '23.11'},
	{id: 'pochinok', logo: ''},
	{id: 'azimov', logo: ''},
	{id: 'drozd', logo: ''},
	{id: 'smolskaya', logo: '', date: '29.05'},
	{id: 'pfandt', logo: ''},
	{id: 'mebert', logo: ''},
	{id: 'didenok', logo: ''},
	{id: 'smolyannikova', logo: ''},
	{id: 'poputarovskaya', logo: ''},
	{id: 'osmanov', logo: ''},
	{id: 'mavlanov', logo: ''},
	{id: 'ogorodov', logo: 'medsi'},
	{id: 'razbirina', logo: ''},
	{id: 'belkevich', logo: ''},
	{id: 'volpert', logo: ''},
	{id: 'valieva', logo: 'sunlight-outdoor', date: '29.05'},
	{id: 'voropaev', logo: ''},
	{id: 'akilhanov', logo: 'missed', date: '29.05'},
	{id: 'romanenko', logo: ''},
	{id: 'tyagay', logo: ''},
	{id: 'sosnovsky', logo: ''},
	{id: 'sidorin', logo: ''},
	{id: 'shipilova', logo: 'shipilova'},
	{id: 'gavrilov', logo: 'roistat'},
	{id: 'chuprov', logo: ''},
	{id: 'anikiev', logo: ''},
	{id: 'nedyakin', logo: ''},
	{id: 'akhadov', logo: ''},
	{id: 'gafarov', logo: 'malikspace'},
	{id: 'prozorov', logo: ''},
	{id: 'gorodetskyi', logo: ''},
	{id: 'panin', logo: ''},
	{id: 'ashepkov', logo: ''},
	{id: 'muslimov', logo: ''},
	{id: 'rakova', logo: 'getresponse'},
	{id: 'dolgov', logo: ''},
	{id: 'gorodetsky_b', logo: ''},
	{id: 'senderov', logo: ''},
	{id: 'palagin', logo: '', date: '23.11'},
	{id: 'kochkin', logo: ''},
	{id: 'satin', logo: ''},
	{id: 'tkachenko', logo: ''},
	{id: 'balakhnin', logo: ''},
	{id: 'belochkina', logo: ''},
	{id: 'obzerin', logo: ''},
	{id: 'afanasieva', logo: ''},
	{id: 'williams', logo: ''},
	{id: 'solomahina', logo: ''},
	{id: 'kamran', logo: ''},
	{id: 'prohorova', logo: ''},
	{id: 'terakopova', logo: ''},
	{id: 'shubina', logo: ''},
	{id: 'davydova', logo: ''},
	{id: 'emelyanov', logo: ''},
	{id: 'odintsova', logo: ''},
	{id: 'filipchenkova', logo: ''},
	{id: 'muradyan', logo: ''},
	{id: 'grishina', logo: ''},
	{id: 'kolomyts', logo: 'ick-expert'},
	{id: 'valinurov', logo: ''},
	{id: 'batyshev', logo: ''},
	{id: 'degtyaryov', logo: ''},
	{id: 'gudimova', logo: ''},
	{id: 'smolny', logo: ''},
	{id: 'doronin', logo: ''},
	{id: 'volovik', logo: ''},
	{id: 'pitercev', logo: ''},
	{id: 'kazantzev', logo: ''},
	{id: 'bermuda', logo: ''},
	{id: 'trabelsi', logo: ''},
	{id: 'prokhorenko', logo: ''},
	{id: 'golovanov', logo: ''},
	{id: 'dozorcev', logo: ''},
	{id: 'sazonova', logo: ''},
	{id: 'andronov', logo: 'cska'},
	{id: 'kolesnichenko', logo: ''},
	{id: 'smolyanov', logo: ''},
	{id: 'zhalilo', logo: ''},
	{id: 'brailovsky', logo: ''},
	{id: 'stepanov', logo: ''},
	{id: 'arutyunov', logo: ''},
	{id: 'mojenkov', logo: 'management-mojenkova'},
	{id: 'mironova', logo: ''},
	{id: 'ivanovp', logo: 'svbd'},
	{id: 'isaeva', logo: 'silk-plaster'},
	{id: 'gribova', logo: ''},
	{id: 'sergyenko', logo: ''},
	{id: 'blagovolina', logo: ''},
	{id: 'reznikova', logo: ''},
	{id: 'mzgireva', logo: ''},
	{id: 'dover', logo: ''},
	{id: 'sarkisov', logo: ''},
	{id: 'kuzavov', logo: ''},
	{id: 'guzenyuk', logo: '', date: '29.05'},
	{id: 'nasibyan', logo: 'nasibyan', date: '29.05'},
	{id: 'satjan', logo: '', date: '29.05'},
	{id: 'losev', logo: '', date: '29.05'},
	{id: 'dmitrieva', logo: '', date: '29.05'},
	{id: 'perkon', logo: 'perkon', date: '29.05'},
	{id: 'young', logo: '', date: '29.05'},
	{id: 'kivokurtsev', logo: '', date: '29.05'},
	{id: 'abbasov', logo: 'abbasov', date: '29.05'},
	{id: 'shonbai', logo: 'shonbai', date: '29.05'},
	{id: 'liang', logo: 'liang', date: '29.05'},
	{id: 'sukhanov', logo: 'sukhanov', date: '29.05'},
	{id: 'bogdanovd', logo: 'bogdanovd', date: '29.05'},
	{id: 'khodjaev', logo: 'khodjaev', date: '29.05'},
	{id: 'neicovcean', logo: '', date: '29.05'},
	{id: 'zamyshlyaev', logo: '', date: '29.05'},
	{id: 'marmer', logo: '', date: '29.05'},
	{id: 'magomedova', logo: '', date: '20.06'},
	{id: 'smetannikova', logo: '', date: '29.05'},
	{id: 'kruglovt', logo: 'kruglovt', date: '29.05'},
	{id: 'khan', logo: '', date: '29.05'},
	{id: 'mirgoyazov', logo: '', date: '29.05'},
	{id: 'gerber', logo: '', date: '29.05'},
	{id: 'chernitsyn', logo: '', date: '29.05'},
	{id: 'emoroz', logo: 'emoroz', date: '29.05'},
	{id: 'birman', logo: '', date: '29.05'},
	{id: 'schurenkov', logo: '', date: '29.05'},
	{id: 'andreev', logo: ''},
	{id: 'stone', logo: '', date: ''},
	{id: 'suzuki', logo: '', date: ''},
	{id: 'hartman', logo: '', date: ''},
	{id: 'ryjakov', logo: '', date: ''},
	{id: 'ketting', logo: '', date: ''},
	{id: 'chumak', logo: '', date: ''},
	{id: 'nevzorova', logo: ''}

]%}


/*
{# Резерв reserv #}
	{id: 'scout', logo: 'myjob'},
	{id: 'hakamada', logo: '', date: '27.06'},
	{id: 'linovich', logo: '', date: '18.07'},
	{id: 'hof', logo: '', date: '11.07'},
	{id: 'charm', logo: '', date: '18.07'},
	{id: 'sinsero', logo: '', date: '27.06', photo_big: true},
	{id: 'pustovit', logo: 'synergy-accelerator'},
	{id: 'muravkina', logo: 'galchonok', date: ''},
	{id: 'glariantov', logo: '', date: ''},
	{id: 'gits', logo: '', date: ''},
	{id: 'azizian', logo: '', date: ''},
	{id: 'mamaev', logo: 'kidburg'},
	{id: 'sivozhelezov', logo: ''},
	{id: 'matary', logo: 'inp'},
	{id: 'rublev', logo: ''},
	{id: 'kirusichev', logo: 'wazzup'},
	{id: 'sergeeva', logo: ''},
	{id: 'lesin', logo: ''},
	{id: 'de-siro', logo: 'ilpatio'},
	{id: 'vulfova', logo: ''},
	{id: 'shark', logo: ''},
	{id: 'kazakov', logo: ''},
	{id: 'mokrov', logo: ''},
	{id: 'karpov', logo: ''},
	{id: 'mir', logo: '', date: ''},
	{id: 'bogdanov', logo: ''},
	{id: 'haybaev', logo: ''},
	{id: 'gabani', logo: ''},
	{id: 'maslov', logo: ''},
	{id: 'mihailov', logo: ''},
	{id: 'gavrikov', logo: ''},
	{id: 'peysakhzon', logo: 'my_target'},
	{id: 'chernov', logo: ''},
	{id: 'soldatkin', logo: ''},
	{id: 'melnik', logo: ''},
	{id: 'levchenko', logo: ''},
	{id: 'beselidze', logo: ''},
	{id: 'chekhranov', logo: ''},
	{id: 'cheryomnikh', logo: ''},
	{id: 'kuzin', logo: ''},
	{id: 'novopashina', logo: ''},
	{id: 'turman', logo: ''},
	{id: 'bereza', logo: ''},
	{id: 'lipaj', logo: ''},
	{id: 'raymm', logo: ''},
	{id: 'aistov', logo: 'tokyo'},
	{id: 'shapkin', logo: ''},
	{id: 'grishenko', logo: ''},
	{id: 'yudovich', logo: ''},
	{id: 'gorsky', logo: ''},
	{id: 'alzubaidi', logo: ''},
	{id: 'moroz', logo: '', date: ''},
	{id: 'bortnikov', logo: '', date: ''},
	{id: 'pushkareva', logo: '', date: ''},
	{id: 'sudakova', logo: '', date: ''},
	{id: 'melnikov', logo: '', date: ''},
	{id: 'troska', logo: '', date: ''},
	{id: 'mishicheva', logo: '', date: ''},
	{id: 'spichakov', logo: '', date: ''},
	{id: 'faisal', logo: 'emc', date: ''},
	{id: 'filippone', logo: 'culinaryion', date: ''},
	{id: 'gerchik', logo: '', date: ''},
	{id: 'freitas', logo: '', date: ''},
	{id: 'zyryanova', logo: 'self-mama', date: ''},
	{id: 'esipova', logo: '', date: ''},
	{id: 'saburov', logo: 'tay-spa'},
	{id: 'gurinovich', logo: 'logo-gurinovich'},
	{id: 'mustafayeva', logo: 'mustafayeva'},
	{id: 'philippone', logo: 'culinaryion', date: ''},
	{id: 'shobanov', logo: ''},
	{id: 'kovpak', logo: ''},
	{id: 'semenikhin', logo: ''},
	{id: 'efremov', logo: ''},
	{id: 'babich', logo: 'rbk'},
	{id: 'makshanov', logo: 'arb'},
	{id: 'shavelev', logo: ''},
	{id: 'kuzovov', logo: ''},
	{id: 'koposov', logo: ''},
	{id: 'strelkova', logo: ''},
	{id: 'golikov', logo: ''},
	{id: 'sysueva', logo: ''},
	{id: 'gralnik', logo: ''},
	{id: 'lokontsev', logo: ''},
	{id: 'gerasimov', logo: ''},
	{id: 'timohina', logo: ''},
	{id: 'grohovskyi', logo: ''},

	{id: 'shahova', logo: 'mshahova'},
	{id: 'kasheev', logo: 'sendsay'},
	{id: 'nosova', logo: 'atol'},
	{id: 'shatyrko', logo: ''},
	{id: 'kazantcev', logo: ''},
	{id: 'bobrova', logo: ''},
	{id: 'indina', logo: ''},
	{id: 'pavlikova', logo: ''},
	{id: 'orlova', logo: ''},
	{id: 'alibaeva', logo: ''},
	{id: 'kovpakeka', logo: ''},
	{id: 'goncharova', logo: ''},
	{id: 'jakuba', logo: ''},
	{id: 'koryanova', logo: 'investo'},
	{id: 'rizvanova', logo: ''},
	{id: 'mikhailichenko', logo: ''},
	{id: 'zelenaya', logo: ''},
	{id: 'dereev', logo: ''},
	{id: 'kucherena', logo: ''},
	{id: 'kuznetsov', logo: 'vse-instrumenty'},
	{id: 'komarova', logo: ''},
	{id: 'gadzhieva', logo: ''},
	{id: 'matita', logo: ''},
	{id: 'alakidze', logo: ''},
	{id: 'milasya', logo: ''},
	{id: 'tagiev', logo: ''},
	{id: 'belonoshenko-e', logo: ''},
	{id: 'igonin', logo: ''},
	{id: 'shpak', logo: ''},
	{id: 'gandapas', logo: 'gandapas'},
	{id: 'batirev', logo: ''},
	{id: 'nikolaeva', logo: ''},
	{id: 'daynekin', logo: 'synergy-book', date: '30/04'},

	{id: 'nesterenko', logo: ''},
	{id: 'ignatieva', logo: ''},
	{id: 'alekseev', logo: ''},
	{id: 'tsatskin', logo: ''},
	{id: 'pavlov', logo: ''},
	{id: 'melnikov', logo: ''},
	{id: 'vetoshkina', logo: ''},
	{id: 'fayziev', logo: ''},
	{id: 'chekalina', logo: ''},
	{id: 'alkhanov', logo: ''}

*/ ?>
